### ISSUE TITLE
how to use ICP on 2D data?

### ISSUE THREAD

**Issue by rebeen** [daviddoria/Examples#10]
I want to apply icp on two TSNE data which are 2D, could you tell me how to use this algorithm please

thank you

**Comment by daviddoria** [comment]
Please contact the appropriate mailing list (pcl-users probably for this?).

**Comment by rebeen** [comment]
sorry but this is the link https://github.com/daviddoria/Examples/blob/master/Python/VTK/ICP.py
am I wrong ?  what do you mean pcl users problem ?
Icp is a part of pcl I know I installed as well but I dont know how to use it for 2D data

**Comment by daviddoria** [comment]
Unfortunately I can't expand all of these examples - I'm saying you should take this example to the mailing list and perhaps someone will be able to show you how to modify it for 2D.

**Comment by rebeen** [comment]
I am sorry but I dont know which mailing list you mean? sorry to have disturbed you

**Comment by daviddoria** [comment]
http://www.pcl-users.org/

**Comment by rebeen** [comment]
thank you very much
